version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    container_name: KinoLite_app

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8000:80"
    depends_on:
      - app
    container_name: KinoLite_nginx

  database:
    image: mysql:latest
    restart: always
    volumes:
      - ./tmp/database:/var/lib/mysql
    ports:
      - "8001:3306"
    environment:
      MYSQL_DATABASE: database_KinoLite
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    container_name: KinoLite_database
